### ISSUE TITLE
邮件内容从标准输入读入

### ISSUE THREAD

**Issue by sintrb** [canovie/smtp-send#1]
开发者你好，我在实际使用中遇到这种情况：我们的应用会把错误写到error.log文件里面，平时在服务器上网可以用"tail -f error.log"命令来持续的查看错误，现在我想让该命令一旦输出的错误信息就通过smtp-send来发送到负责人的邮箱上，有点类似"tail -f error.log | smtp-send xxx"这样的调用方式，请问这样的情况怎么处理会方便点。重新写代码是能够实现的，但我觉得你的smtp-send已经很方便了，我们在定时发送汇总信息的时候就在用它，想着继续用它那我们就可以一套通用了。
最后，谢谢你开发并分享smtp-send。

**Comment by canovie** [comment]
我觉得可以有，不过可能得过些时间了，最近有点忙:runner:

**Comment by canovie** [comment]
> 开发者你好，我在实际使用中遇到这种情况：我们的应用会把错误写到error.log文件里面，平时在服务器上网可以用"tail -f error.log"命令来持续的查看错误，现在我想让该命令一旦输出的错误信息就通过smtp-send来发送到负责人的邮箱上，有点类似"tail -f error.log | smtp-send xxx"这样的调用方式，请问这样的情况怎么处理会方便点。重新写代码是能够实现的，但我觉得你的smtp-send已经很方便了，我们在定时发送汇总信息的时候就在用它，想着继续用它那我们就可以一套通用了。
> 最后，谢谢你开发并分享smtp-send。
我觉得可以有，不过可能得过些时间了，最近有点忙:runner:

**Comment by alphajc** [comment]
> 开发者你好，我在实际使用中遇到这种情况：我们的应用会把错误写到error.log文件里面，平时在服务器上网可以用"tail -f error.log"命令来持续的查看错误，现在我想让该命令一旦输出的错误信息就通过smtp-send来发送到负责人的邮箱上，有点类似"tail -f error.log | smtp-send xxx"这样的调用方式，请问这样的情况怎么处理会方便点。重新写代码是能够实现的，但我觉得你的smtp-send已经很方便了，我们在定时发送汇总信息的时候就在用它，想着继续用它那我们就可以一套通用了。
> 最后，谢谢你开发并分享smtp-send。

我觉得可以有，不过可能得过些时间了，最近有点忙:runner:
